package trade.kuharchuk.cryptocompare.domain;

public enum AssetSortBy {
  CREATED_ON,
  LAUNCH_DATE,
  UPDATED_ON,
  PRICE_USD,
  CIRCULATING_MKT_CAP_USD,
  TOTAL_MKT_CAP_USD,
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_DIRECT_USD,
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_DIRECT_USD,
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_TOP_TIER_USD,
  SPOT_MOVING_24_HOUR_QUOTE_VOLUME_USD,
  SPOT_MOVING_24_HOUR_CHANGE_USD,
  SPOT_MOVING_24_HOUR_CHANGE_PERCENTAGE_USD,
  TOTAL_ENDPOINTS_WITH_ISSUES
}
