package trade.kuharchuk.cryptocompare.domain;

public enum AssetFieldGroup {
  ID,
  BASIC,
  SUPPORTED_PLATFORMS,
  CUSTODIANS,
  SECURITY_METRICS,
  SUPPLY,
  SUPPLY_ADDRESSES,
  ASSET_TYPE_SPECIFIC_METRICS,
  SOCIAL,
  TOKEN_SALE,
  EQUITY_SALE,
  RESOURCE_LINKS,
  CLASSIFICATION,
  PRICE,
  MKT_CAP,
  VOLUME,
  CHANGE,
  TOPLIST_RANK,
  DESCRIPTION,
  DESCRIPTION_SUMMARY,
  CONTACT,
  SEO,
  INTERNAL
}
